### ISSUE TITLE
Exercises tracking issue

### ISSUE THREAD

**Issue by gr2m** [gr2m/advanced-react-patterns#1]
- [ ] Context Module Functions
- [ ] Compound Components
- [ ] Flexible Compound Components
- [ ] Prop Collections and Getters
- [ ] State Reducer
- [ ] Control Props

**Comment by gr2m** [comment]
Note to self and others interested, here is how I setup this repository using the [GitHub CLI](https://cli.github.com/)

This command will create a new `advanced-react-patterns` folder in the current directory and setup git.

```
gh repo fork kentcdodds/advanced-react-patterns
```

Change directory into `advanced-react-patterns` and run the setup script

```
cd advanced-react-patterns
node setup
```

Remove the `.github/workflows/validate.yml` workflow. Add [`.github/workflows/test.yml`](https://github.com/gr2m/advanced-react-patterns/blob/cb4e6fb87bdf231f524ab49b869376d2d026ad62/.github/workflows/test.yml) instead. Commit and push the change. This will add proper CI to your pull requests :)

Now go to the repositorie's Actions tab and enable actions.

Enable issues in your fork's settings, then create a tracking issue with all excercises:

```md
- [ ] Context Module Functions
- [ ] Compound Components
- [ ] Flexible Compound Components
- [ ] Prop Collections and Getters
- [ ] State Reducer
- [ ] Control Props
```

Create an issue for each exercise as I get there. Then create a pull request once I finish the exercise. Example: #3

Rinse & repeat until all exercises are done 🎉
